### ISSUE TITLE
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.

### ISSUE THREAD

**Issue by geyang** [escherpad/luna-saga#1]
This is because `luna-saga` is compiled targeting ES6.

In your webpack project, add the luna-saga library to the list of files to be processed by babel.

**Comment by episodeyang** [comment]
I could add a processing step to make the module usable without es6 preprocessing, but will do it later because generator themselves are also not supported well yet. 

For now, you just need to add the following to your web pack.config.json

```javascript
      {
        // ES6 modules
        test: /luna\-saga\/(.*)\.js$/,
        loaders: ['regenerator', 'react-hot', 'babel-loader']
      },
```
